# Generated by Django 6.1 on 2026-08-27 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart',
            name='cart_owner_xor',
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('guest_token__isnull', True)), models.Q(('user__isnull', True), ('guest_token__isnull', False)), _connector='OR'), name='cart_owner_xcart'),
        ),
    ]
